travis:
  secure:
    BINSTAR_TOKEN: lQiQHIyJiVAJYNX1L8SuMjmRJLIRCZ5r8f3czDLdSSs2BixrmZL4QVGqAEgugkNIS/dgP9x6Oih6iYudrkXP9J0NqF/Gf9+U1gezk3ivZQ+90o3Y71w1zDKaqlQ14zKWxNtDR0kBL6uqqq07pdbxagdQO2XqjMrR7fTl9BDNrGSfByS9ogwh7o7f0YUHX4DPlzWNoYn8pgL4vWI6u/VQhy0mLI5tEOWTK6K7l2PbQf4r3tzFrkVffP/REnqJ4DXFzQBBhwlI9GY2kqlk0DEmaL78rGh7/1KBf9JRaKI6/uj8lHusYwO/bpisZSFlX1eRsSr/67+5+xNOc/+XRrrrEvDUgsMKAPnLe3ieR2YRdGfHpNiNjeLBGQLl7FfQehkZWsymveId4fNTt9hItNCIX+INIaYsi07hXi/QyabeOha8s6GEFmN9GPMVWY+aHWtTv64STdTIqfTm27Ni0MIG/eTjUe0Sz9ZTOvT58on0xDJUW621qGrTqV+Fy3KBjFVPG35FMkdz5xXRAFBSXVFrz55EXOVFjzcec2pmNwLZjaFGUnLRbsE+eGCcXA1XqfolPDZekLVimWb/oEyPFruHdW5YhQz/sD2Fx3/XnA9/9WFIJX8KSKEB765M0iev8HVDHwtMmT+/5C/4J5YtYPd25S+m4YB4I3NcCT3PG4f9WgQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
